name: First Workflow
on: workflow_dispatch #reserved key-word
jobs: #reserved key-word
  first_job:
    runs-on: ubuntu-latest #reserved key-word
    steps: #reserved key-word
      - name: print greeting
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Goodbye"
      
